# Álgebra Lineal con Python

Recordemos que si damos $n\times m$ números reales, entonces podemos crear un arreglo (una matriz):
$$A_{m\times n}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

y al conjunto de matrices con coeficientes en $\mathbb{R}$ lo denotamos $\text{Mat}_{m\times n}(\mathbb{R})$.


### Variables
$$\text{nombre} = \text{objeto}$$

Debug: $\text{print(variable)}$

1. Suma de matrices

$$\begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} + \begin{pmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{pmatrix} = \begin{pmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{pmatrix}$$

2. Multiplicación de matrices

$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \times \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{pmatrix} $$

### Listas

$L=[a_{0}, a_{1}, \dots, a_{n-1}]$

In [ ]:
L = [1, 2, 3, 4, 5]

M = [6, 7, 8, 9 , 10]

N = [11, 12, 13]

print(L)
print(M)  # me muestra el resultado
print(N)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13]


In [ ]:
type(L)

list

In [ ]:
L_set = set(L)

L_set

{1, 2, 3, 4, 5}

In [ ]:
L_lista = list(L_set)
L_lista

[1, 2, 3, 4, 5]

In [ ]:
L + M # concatena (no realiza operaciones vectoriales).

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
L + M + N

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

### NumPy

- Un vector = arreglo 1D en Python
- Una matriz = arreglo 2D en Python

In [ ]:
import numpy as np

In [ ]:
L_vector = np.array(L) # Convertir una lista en un vector

L_vector

array([1, 2, 3, 4, 5])

In [ ]:
type(L_vector)

numpy.ndarray

In [ ]:
M_vector = np.array(M)

N_vector = np.array(N)

print(M_vector)
print(N_vector)

[ 6  7  8  9 10]
[11 12 13]


In [ ]:
len(L_vector), len(M_vector), len(N_vector)

(5, 5, 3)

In [ ]:
L_vector + M_vector # suma vectorial

array([ 7,  9, 11, 13, 15])

## Creando matrices con NumPy: El método `solve( , )`


In [ ]:
A = np.array([1, 2, 1, 3]).reshape((2,2))
A

array([[1, 2],
       [1, 3]])

In [ ]:
B = np.array([1,3])

$$AX=B$$

In [ ]:
X = np.linalg.solve(A,B)

X

[-3.  2.]
