In [1]:
import numpy as np


Código para realizar operaciones elementales por renglones.



In [2]:
5**2


25

In [3]:
def Vale(x,n):
  y = x**n
  return y

In [4]:
Vale(9.2,3)


778.6879999999999

In [5]:
6 % 2


0

In [6]:
# loops ciclos
indice = [1, 2, 3, 4, 5]

pares = [x for x in indice if x%2==0]

pares

[2, 4]

In [7]:
[x for x in range(1,6)]


[1, 2, 3, 4, 5]

##Coefientes de una matriz: acceso en numpy

In [8]:
A = np.array([[2, 1, 0.5], [1, 0 ,0 ], [2, 1, 0], [5, -1, 3] ] )

A


array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [9]:
A.shape


(4, 3)

In [10]:
indice

[1, 2, 3, 4, 5]

In [11]:
# La indexación en Python comienza en 0

print(indice[0])
print(indice[4])

1
5


In [12]:
A.shape[0] # número de columnas de la matriz A

4

In [13]:
A.shape[1] # número de renglones de la matriz A


3

In [14]:
A

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [15]:
A[0] # primer renglón

array([2. , 1. , 0.5])

In [16]:
A[3][1]


-1.0

In [17]:
B = np.copy(A)
B

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [18]:
def RowSwap(A,k,l):
# =============================================================================
#     A  NumPy array.  RowSwap devolverá una matriz duplicada con filas
# k y l intercambiados.
# =============================================================================
    m = A.shape[0]  # m renglones
    n = A.shape[1]  # n columnas

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A NumPy array.  RowScale devolverá una matriz duplicada con el
# entradas de la fila k multiplicadas por escala..
# =============================================================================
    m = A.shape[0]  # m renglones
    n = A.shape[1]  # n columnas

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A numpy array.  RowAdd devolverá matriz duplicada con fila
# l modificado. Los nuevos valores serán los valores antiguos de la fila l agregados a
# los valores de la fila k, multiplicados por la escala.
# =============================================================================
    m = A.shape[0]  # m renglones
    n = A.shape[1]  # n columnas

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B


In [19]:

A

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [20]:
RowSwap(A,0,1)


array([[ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0.5],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [21]:
RowScale(A, 0, 0.5)


array([[ 1.  ,  0.5 ,  0.25],
       [ 1.  ,  0.  ,  0.  ],
       [ 2.  ,  1.  ,  0.  ],
       [ 5.  , -1.  ,  3.  ]])

In [22]:
A

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [23]:
RowAdd(A, 0, 1, 2)


array([[ 2. ,  1. ,  0.5],
       [ 5. ,  2. ,  1. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])